<!DOCTYPE html>
<html>

<head>
</head>

<body>
    <script>
        //Using try and catch

        function simpleTryCatch() {
            let result;

            try {
                result = x / 10;
            } catch (error) {
                console.log(error.message);
            }
        }
        simpleTryCatch();

        //Using try, catch and finally

        function finallyCatchSample() {
            let result;

            try {
                console.log('An error will occur.');
                result = x / 10;
                console.log('This line will never run.')
            } catch (error) {
                console.log('In the catch block: ' + error.message);
            } finally {
                console.log('In the \'finally\' block');
            }
        }

        finallyCatchSample();

        //Using throw custom error object

        function throwError() {
            try {
                attemptDivision();
            } catch (error) {
                console.log(error.message + " - Error.type: " + error.name);
            }
        }

        function attemptDivision() {
            let result;

            try {
                result = x / 10;
            } catch (error) {
                throw {
                    "message": "In the attemptDevision() method the following error occured: " + error.message,
                    "name": "CustomError"
                };
            }
        }

        throwError();

        // Check for type of error

        function referenceError() {
            let result;

            try {
                // Reference error because 'x' is not defined
                result = x / 10;
            } catch (error) {
                handleError(error);
            }
        }

        function rangeErrorSample() {
            let result = 0;

            try {
                // Range error because a number cannot have 200 significant digits
                result.toPrecision(200);
            } catch (error) {
                handleError();
            }
        }

        function typeErrorSample() {
            let result = 0;

            try {
                // Type error because result is a numeric
                result.toUpperCase();
            } catch (error) {
                handleError(error);
            }
        }

        function uriErrorSample() {
            let uri = "http://www.netinc.com/path%%%/file name";

            try {
                // URI error
                decodeURI(uri);
            } catch (error) {
                handleError(error);
            }
        }

        function syntaxErrorSample() {
            try {
                // Syntax error because missing a final single quote
                let sum = eval("alert('Hello)");
            } catch (error) {
                handleError(error);
            }
        }

        function handleError(error) {
            switch (error.name) {
                case "ReferenceError":
                    console.log("Reference error: " + error.message);
                    break;
                case "RangeError":
                    console.log("Range error: " + error.message);
                    break;
                case "TypeError":
                    console.log("Type error: " + error.message);
                    break;
                case "URIError":
                    console.log("URI error: " + error.message);
                    break;
                case "SyntaxError":
                    console.log("Syntax error: " + error.message);
                    break;
                case "EvalError":
                    console.log("Evaluation error: " + error.message);
                    break;
                default:
                    console.log("Error Type: " + error.name + " - Message: " + error.message);
                    break;
            }
        }
    </script>
</body>

</html>